version: 2.1
orbs:
  newman: postman/newman@1.0.0
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: OHPEN_GITHUB.postman_collection.json
          environment: GITHUB-ENV-TST.postman_environment.json
          iteration-data: inputData.json
          additional-options: -r cli,junit

          